---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-processor
  name: payment-processor
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: payment-processor
